### PR TITLE
fix(utils): remove outdated code in utils script

### LINKED ISSUE #165: Error: Could not load rockspec file /apisix/./rockspec/apisix-master-0.rockspec (Error loading file: [string "/apisix/./rockspec/apisix-master-0.rockspec"]:77: '}' expected (to close '{' at line 33) near '.') The command '/bin/sh -c /install-common.sh install_apisix     && /determine-dist.sh' returned a non-zero code: 1 make: *** [Makefile:121: build-apisix-rpm] Error 1
cause by sed 
```bash
https://github.com/api7/apisix-build-tools/blob/master/utils/install-common.sh#L77
```

Error build action
> https://github.com/api7/apisix-build-tools/runs/5429589069?check_suite_focus=true
```bash
Error: Could not load rockspec file /apisix/./rockspec/apisix-master-0.rockspec (Error loading file: [string "/apisix/./rockspec/apisix-master-0.rockspec"]:77: '}' expected (to close '{' at line 33) near '.')
The command '/bin/sh -c /install-common.sh install_apisix     && /determine-dist.sh' returned a non-zero code: 1
make: *** [Makefile:121: build-apisix-rpm] Error 1
```

> for https://github.com/apache/apisix/blob/master/rockspec/apisix-master-0.rockspec Added 

```bash
dependencies = {
    "net-url = 0.9-1",
}
```

replaced with sed result
```bash
dependencies = {
    "net-url = "./apisix",
}
```
I think this https://github.com/api7/apisix-build-tools/blob/master/utils/install-common.sh#L77 sed maybe need update

### PR DESCRIPTION
**Pull request by leslie-tsang**
fix #165 

PR https://github.com/api7/apisix-build-tools/pull/167 need to be merged first to fix the CentOS 8 broken CI

### CODE REVIEW

**Comment by leslie-tsang** [comment]
@spacewander PTAL

File: utils/install-common.sh [hunk 1]
```diff
@@ -69,13 +87,8 @@ is_newer_version() {
 }
 
 install_apisix() {
-    # show awk version
-    awk --version
     mkdir -p /tmp/build/output/apisix/usr/bin/
     cd /apisix
-    # remove useless code for build
-    sed -i 's/url.*/url = ".\/apisix",/' rockspec/apisix-master-${iteration}.rockspec
-    sed -i 's/branch.*//' rockspec/apisix-master-${iteration}.rockspec
```
Comment (spacewander) [inline utils/install-common.sh:78]: Interesting. Is it safe to remove them?

Comment (leslie-tsang) [reply utils/install-common.sh:78]: I test it on my local machine and check the logic, it should be safe to remove them

All the CI passed :)

Comment (spacewander) [reply utils/install-common.sh:78]: Look like we will download the APISIX from master instead of using the local directory. (Note that the CI only check the basic proxy function)

Comment (leslie-tsang) [reply utils/install-common.sh:78]: > Look like we will download the APISIX from master instead of using the local directory. (Note that the CI only check the basic proxy function)

I will test it today, thanks for the tips.

Comment (leslie-tsang) [reply utils/install-common.sh:78]: After test, I believe that it is safe to remove them.  :)

**Review by tzssangglass — APPROVED** [review]

**Review by spacewander — APPROVED** [review]
